"""Add a Comments Table.

Revision ID: 30acbfa9b86b
Revises: ba9731c5ba8b
Create Date: 2019-04-23 11:38:27.938281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30acbfa9b86b'
down_revision = 'ba9731c5ba8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_content', sa.String(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
